Hotel_room_book/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admn/', admin.site.urls),
    path('',include('user.urls')),
    path('admin/',include('admn.urls')),
    path('hotel/',include('hotel.urls')),
    path('accounts/',include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admn/urls.py
from django .urls import path
from . import views


urlpatterns=[ 
    path('',views.admin_login,name='admin_login'),
    path('admin_home',views.admin_home,name='admin_home'),
    path('admin_logout',views.admin_logout,name='admin_logout'),
    path('create_hotel',views.create_hotel,name='create_hotel'),
    path('hotel_view',views.hotel_view,name='hotel_view'),
    path('hotel_edit/<int:id>/',views.hotel_edit,name='hotel_edit'),
    path('hotel_delete/<int:id>/',views.hotel_delete,name='hotel_delete'),
    path('user_view',views.user_view,name='user_view'),
    path('user_edit/<int:id>/',views.user_edit,name='user_edit'),
    path('user_delete/<int:id>/',views.user_delete,name='user_delete'),
    path('refoffer',views.refoffer,name='refoffer'),
    path('offeredit/<int:id>/',views.offeredit,name='offeredit'),
    path('offerstatus/<int:id>/<str:value>/',views.offerstatus,name='offerstatus'),
    path('userBlock/<int:id>/',views.userBlock,name='userBlock'),
    path('hotelblock/<int:id>/',views.hotelblock,name='hotelblock'),
    path('vip',views.vip,name='vip'),
    path('viphotel',views.viphotel,name='viphotel'),
    path('viproom',views.viproom,name='viproom'),
    path('location',views.location,name='location'),
   path('hotel',views.hotel,name='hotel'),
    path('act/<int:id>/<str:value>/',views.act,name='act'),



]

hotel/urls.py
from django .urls import path
from . import views


urlpatterns=[ 
    path('',views.hotel_log,name='hotel_log'),
    path('hotel-home/<int:id>/',views.hotel_home,name='hotel_home'),
    path('hotel_logout',views.hotel_logout,name='hotel_logout'),
    path('hotel_rooms/<int:id>/',views.hotel_rooms,name='hotel_rooms'),
    path('add_room/<int:id>/',views.add_room,name='add_room'),
    path('hotel_profile/<int:id>/',views.hotel_profile,name='hotel_profile'),
    path('hotel_update/<int:id>/',views.hotel_update,name='hotel_update'),
    path('room_edit/<int:id>/',views.room_edit,name='room_edit'),
    path('room_delete/<int:id>/',views.room_delete,name='room_delete'),
    path('hotel_user/<int:id>/',views.hotel_user,name='hotel_user'),
    path('hotel_booked/<int:id>/',views.hotel_booked,name='hotel_booked'),
    path('booking_detail/<int:id>/',views.booking_detail,name='booking_detail'),
    path('confirm/<int:id>/<str:value>/',views.confirm,name='confirm'),


]

admn/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.




class Hoteladmin(models.Model):

    hotel_name=models.CharField(max_length=200,null=True)
    username=models.CharField(max_length=200,null=True)
    password=models.CharField(max_length=200,null=True)
    is_active = models.BooleanField(default=True)
    location=models.CharField(max_length=200,null=True)
    contact=models.BigIntegerField()
    description=models.TextField(max_length=1000,verbose_name='description')
    categories=models.CharField(max_length=200,null=True)
    hotelimage1=models.ImageField(null=True ,blank=True)


    @property
    def get_lowest_price(self):
        try:
            rooms =self.rooms_set.all()
            price=[]
            
            for room in rooms:
                price.append(room.room_price)
            
            lowest_price=min(price)
        except:
            lowest_price='NOT ENTERD'
        return lowest_price


    @property
    def imageURL(self):
        try:
            url= self.hotelimage1.url
        except:
            url=''
        return url
            

            

class Customer(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, null=True,blank=True)
    name=models.CharField(max_length=200,null=True)
    email=models.CharField(max_length=200,null=True)
    reff_code = models.CharField(max_length=100, null= True)
    refferd_user = models.CharField(max_length=150, null= True)
    

class Features(models.Model):
    hotel=models.ForeignKey(Hoteladmin,on_delete=models.SET_NULL,null=True,blank=True)
    Free_wifi=models.BooleanField(default=False)
    Loundry_service=models.BooleanField(default=False)
    Swimming_pool=models.BooleanField(default=False)
    Restaurant=models.BooleanField(default=False)
    Parking=models.BooleanField(default=False)

class Hotel_image(models.Model):
    hotel=models.ForeignKey(Hoteladmin,on_delete=models.SET_NULL,null=True,blank=True)
    image=models.ImageField(null=True ,blank=True)

class Rooms(models.Model):
    hotel=models.ForeignKey(Hoteladmin,on_delete=models.SET_NULL,null=True,blank=True)
    room_type=models.CharField(max_length=200,null=True)
    # room_description=models.TextField(max_length=1000,verbose_name='description')
    sleeps=models.CharField(max_length=200,null=True)
    room_price=models.FloatField()
    room_image1=models.ImageField(null=True ,blank=True)
    room_image2=models.ImageField(null=True ,blank=True)
    room_image3=models.ImageField(null=True ,blank=True)
    room_available=models.IntegerField()


class Room_features(models.Model):
    hotel= models.ForeignKey(Hoteladmin,on_delete=models.SET_NULL,null=True,blank=True)
    room=models.ForeignKey(Rooms,on_delete=models.SET_NULL,null=True,blank=True)
    Free_wifi=models.BooleanField(default=False)
    king_size_bed=models.BooleanField(default=False)
    TV=models.BooleanField(default=False)
    Bath_Tube=models.BooleanField(default=False)
    Safe_box=models.BooleanField(default=False)
    Welcome_bottle=models.BooleanField(default=False)
    Breakfast=models.BooleanField(default=False)
    Lunch=models.BooleanField(default=False)
    Dinner=models.BooleanField(default=False)
    

class Room_image(models.Model):
    room=room=models.ForeignKey(Rooms,on_delete=models.SET_NULL,null=True,blank=True)
    image=models.ImageField(null=True ,blank=True)




class Booking(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.SET_NULL,null=True,blank=True)
    hotel=models.ForeignKey(Hoteladmin,on_delete=models.SET_NULL,null=True,blank=True)
    date_booked=models.DateField(auto_now=True)
    check_in=models.DateField(null=True,blank=True)
    check_out=models.DateField(null=True,blank=True)
    complete=models.BooleanField(default=False,null=True,blank=True)
    total_price=models.BigIntegerField(default=0,null=True,blank=True)
    payment_status=models.CharField(max_length=200,null=True)
    total_guest=models.CharField(max_length=200,null=True)
    cancel=models.BooleanField(default=False,null=True,blank=True)
    confirm=models.BooleanField(default=False,null=True,blank=True)
    
    @property
    def total_rooms(self):
        roombooked=self.roombooked_set.all()
        total=sum(room.quantity for room in roombooked)
        return total
        

class Roombooked(models.Model):
    room=models.ForeignKey(Rooms,on_delete=models.SET_NULL,null=True,blank=True)
    booking=models.ForeignKey(Booking,on_delete=models.SET_NULL,null=True,blank=True)
    quantity=models.IntegerField(default=0,null=True,blank=True)
    date_added = models.DateField(auto_now_add=True)
    

    @property
    def get_total(self):
        total = self.room.room_price * self.quantity
        return total




class reffreal_offer(models.Model):
    ref_name = models.CharField(null = True, max_length=225)
    ref_discount = models.IntegerField(null = True)
    ref_price = models.IntegerField(null = True)
    referd_person_discount = models.IntegerField(null = True)
    order_maximum = models.IntegerField(null = True)
    ref_status = models.BooleanField(null=True,default=True)
    offer_type=models.CharField(max_length=200,null=True)


class VIP(models.Model):
    hotel=hotel=models.ForeignKey(Hoteladmin,on_delete=models.SET_NULL,null=True,blank=True)
    room=models.ForeignKey(Rooms,on_delete=models.SET_NULL,null=True,blank=True)
    status= models.BooleanField(null=True,default=True)
    

hotel/models.py
from django.db import models

# Create your models here.

templates/hotel/booking_detailed.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>

<body>
<div class="container">
    <div class="head p-5">
        

    </div>
</div>
    <div class="container border">
        <div class="row">

            <div class="col-md-12">
                <div class="row border-bottom m-3">
                    <div class="col-md-6">
                        <div class="float-left">
                            <h2>Booking Id</h2>
                            <p>{{booking.id}}</p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="float-right">
                            <p>Booked by {{booking.customer.name}} on {{booking.date_booked}}
                            </p>
                        </div>
                    </div>
                </div>

                <div class="row border-bottom m-3">
                    <div class="col-md-12">
                        <div class="subheading">
                            <h3>{{booking.hotel.hotel_name}}</h3>
                        </div>
                        <div class="pt-5">
                            <h4>
                               HOTEL LOCATION

                            </h4>
                            <p>
                                {{booking.hotel.location}}
                            </p>
                        </div>
                    </div>
                </div>

                <div class="row m-3 border-bottom pt-3">
                    <div class="col-sm-6 col-md-3 ">
                        <div>

                            <p>
                                Primary Guest
                            </p>
                            <h4>{{booking.customer.name}}</h4>

                        </div>
                        <div class="pt-3">
                            <p>
                                Mobile Number
                            </p>
                            <h5>{{user.last_name}}</h5>
                        </div>
                        <div class="pt-3">
                            <p>
                                email
                            </p>
                            <h5>{{user.email}}</h5>
                        </div>

                    </div>
                    <div class="col-sm-6 col-md-3 text-center">
                        <div>

                            <p>
                                CHECKIN
                            </p>
                            <h5>{{booking.check_in}}</h5>

                        </div>
                        <div class="pt-4">
                            <p>
                                checkout
                            </p>
                            <h5>{{booking.check_out}}</h5>
                        </div>

                    </div>
                    <div class="col-sm-6 col-md-3 text-center">
                        <div>

                            <p>
                                check in time
                            </p>
                            <h5>12:00 PM</h5>

                        </div>
                        <div class="pt-4">
                            <p>
                                check out time
                            </p>
                            <h5>11:00 AM</h5>
                        </div>


                    </div>
                    <div class="col-sm-6 col-md-3">
                        <div class="col-md-12">
                            <h3 class="text-center">{{date.days}} NIGHT</h3>
                        </div>
                       
                            <div class="col-md-12 pt-5">
                               Guest: {{booking.total_guest}}
    
                            </div>
                            <div class="col-md-12 pt-5">
                               Room:{{booking.total_rooms}}
                            </div>
                       

                    </div>
                    
                </div>

            <div class="row m-3 border-bottom pt-5">
                <div class="col-md-12 ">
                        <h2>Payment Status</h2>
                        <table class="table">
                            <thead>
                                
                              <tr>
                                
                                <th scope="col">ROOM</th>
                                <th scope="col">Price Per Night</th>
                                <th scope="col">selected</th>
                                <th scope="col">total</th>
                                
                              </tr>
                            </thead>
                            <tbody>
                                {%for rooms in booking.roombooked_set.all %}
                              <tr>
                                
                                <td>{{rooms.room.room_type}}</td>
                                <td>{{rooms.room.room_price}}</td>
                                <td>{{rooms.quantity}}</td>
                                <td>{{rooms.get_total}}</td>
                              </tr>
                              {%endfor%}
                          </table>
                        
                          <div class="col-md-12">
                              <div class="col-md-6">

                              </div>
                              <div class="col-md-6 float-right pl-5">
                                  <div>
                                      <h5 class="p-3">
                                          DAYS:{{date.days}}
                                      </h5>
                                      <h3 class="p-3">
                                          Total Price:{{booking.total_price}}
                                      </h3>

                                  </div>

                              </div>
                          </div>

                </div>

            </div>
                

            </div>





        </div>

        <div class="text-center">
            <button onclick="printpage()" type="button" class="btn btn-outline-primary">Print</button>
    </div>
    </div>
    </div>

<script>
    function printpage(){
 window.print();
}
</script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
</body>

</html>

templates/hotel/hotel-login.html
<div class="log">
    <h2>Welcome Back</h2>
    <form action="{%url 'hotel_log' %}" method="POST">
        {% csrf_token %}
      <div class="input-cont">
        <input type="text" name="username">
        <label>Username</label>
        <div class="border1"></div>
      </div>
      <div class="input-cont">
        <input type="password" name="password">
        <label>Password</label>
        <div class="border2"></div>
      </div>
      
      
      <div class="clear"></div>
      <input type="submit" value="Sign In"> 
      {%for message in messages %}
            <p style="color: red;" id="message_container">{{message}}</p>
        {%endfor%} 
    </form>
</div>
<script>
  var message_ele = document.getElementById("message_container");

  setTimeout(function () {
      message_ele.style.display = "none";
  }, 3000);
</script>

<style>
    * {
  box-sizing: border-box;
}
body {
  background-color: #EEE;
}
.clear {
  clear: both;
}
.log {
  width: 400px;
  margin: 5% auto;
  background-color: #FFF;
  padding: 30px 0;
}
.log h2 {
  text-align: center;
  color: #ed2553;
  font-weight: bold;
  font-size: 26px;
  margin-bottom: 50px;
}
.log .input-cont {
  position: relative;
  margin: 0 50px 60px;
}
.log .input-cont:last-of-type {
  margin-bottom: 30px;
}
.log .input-cont input {
  position: relative;
  z-index: 1;
  width: 100%;
  height: 40px;
  outline: none;
  color: #212121;
  font-size: 22px;
  font-weight: 400;
  background: none;
  border: none;
}
.log .input-cont input:focus {
  outline: none;
}
.log .input-cont label {
  position: absolute;
  color: #948c8c;
  top: 0;
  left: 0;
  line-height: 40px;
  -webkit-transition: .3s;
  -moz-transition: .3s;
    -o-transition: .3s;
       transition: .3s;
}
.log .input-cont input:focus + label {
  margin-top: -30px;
  -webkit-transform: scale(.8);
  -moz-transform: scale(.8);
    -o-transform: scale(.8);
    transform: scale(.8);
  color: #bdbdbd;
}
.log .border1,
.log .border2 {
  position: absolute;
  height: 1px;
  background-color: #9E9E9E;
  left: 0;
  bottom: 0;
  width: 100%;
}
.log .border1::after,
.log .border1::before,
.log .border2::after,
.log .border2::before {
  content: "";
  position: absolute;
  bottom: 0;
  width: 0;
  height: 2px;
  -webkit-transition: .5s;
  -moz-transition: .5s;
    -o-transition: .5s;
       transition: .5s;
}
.log .border1::after,
.log .border2::after {
  
  right: 50%;
  background-color: #ed2553;
}
.log .border1::before,
.log .border2::before {
  left: 50%;
  background-color: #ed2553;
}
.log .input-cont input:focus ~ .border1::after,
.log .input-cont input:focus ~ .border1::before,
.log .input-cont input:focus ~ .border2::after,
.log .input-cont input:focus ~ .border2::before {
  width: 50%;
}
.log .check,
.log a {
  float: left;
  width: calc(50% - 50px);
  display: block;
  font-size: 12px;
  margin-bottom: 30px;
}
.log .check {
  margin-left: 50px;
}
.log a {
  text-align: right;
  text-decoration: none;
  color: #ed2553;
}
.log a:hover {
  text-decoration: underline;
  color: #F00;
}
.log form input[type="submit"] {
  display: block;
  margin: 0 auto 20px;
  border: 2px solid transparent; 
  padding: 5px 20px;
  font-size: 22px;
  cursor: pointer;
  color: #ed2553;
  -webkit-transition: .5s;
  -moz-transition: .5s;
    -o-transition: .5s;
       transition: .5s;
}
.log form input[type="submit"]:focus {
  outline: none; 
}
.log form input[type="submit"]:hover {
  border: 2px solid #ed2553; 
}

</style>

templates/hotel/hotel-rooms.html
{% extends 'hotel/hotel-base.html' %}
{% load static %}
{% block content %}
<!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round"> -->

<style>
    * {box-sizing: border-box}
body {font-family: Verdana, sans-serif; margin:0}
.mySlides {display: none}
img {vertical-align: middle;}

/* Slideshow container */
.slideshow-container {
  max-width: 1000px;
  position: relative;
  margin: auto;
}

/* Next & previous buttons */
.prev, .next {
  cursor: pointer;
  position: absolute;
  top: 50%;
  width: auto;
  padding: 16px;
  margin-top: -22px;
  color: white;
  font-weight: bold;
  font-size: 18px;
  transition: 0.6s ease;
  border-radius: 0 3px 3px 0;
  user-select: none;
}

/* Position the "next button" to the right */
.next {
  right: 0;
  border-radius: 3px 0 0 3px;
}

/* On hover, add a black background color with a little bit see-through */
.prev:hover, .next:hover {
  background-color: rgba(0,0,0,0.8);
}

/* Caption text */
.text {
  color: #f2f2f2;
  font-size: 15px;
  padding: 8px 12px;
  position: absolute;
  bottom: 8px;
  width: 100%;
  text-align: center;
}

/* Number text (1/3 etc) */
.numbertext {
  color: #f2f2f2;
  font-size: 12px;
  padding: 8px 12px;
  position: absolute;
  top: 0;
}

/* The dots/bullets/indicators */
.dot {
  cursor: pointer;
  height: 15px;
  width: 15px;
  margin: 0 2px;
  background-color: #bbb;
  border-radius: 50%;
  display: inline-block;
  transition: background-color 0.6s ease;
}

.active, .dot:hover {
  background-color: #717171;
}

/* Fading animation */
.fade {
  -webkit-animation-name: fade;
  -webkit-animation-duration: 1.5s;
  animation-name: fade;
  animation-duration: 1.5s;
}

@-webkit-keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}

@keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}

/* On smaller screens, decrease text size */
@media only screen and (max-width: 300px) {
  .prev, .next,.text {font-size: 11px}
}
</style>

   <link rel="stylesheet" href="{% static 'hotel/rooms-table/css/main.css' %}">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-6">
						<h2>Manage <b>Rooms</b></h2>
					</div>
					<div class="col-sm-6">
						<a href="{% url 'add_room' hotel.id %}" class="btn btn-success" ><i class="material-icons">&#xE147;</i> <span>Add New Rooms</span></a>
						
					</div>
                </div>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>
            
            
                        </th>
                        <th>Room Type</th>
                        <th>Price</th>
                        <th>sleeps</th>
                        <th>Features</th>
                        <th>Total Rooms</th>
                        <!-- <th>Room Feature</th> -->
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for room in rooms %}
                    <tr>
            
                        <td>
                           
                            
                            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                                <ol class="carousel-indicators">
                                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                                </ol>
                                <div class="carousel-inner">
                                    {% for images in room.room_image_set.all %}
                                    {% if forloop.first %}
                                    <div class="carousel-item active">
                                        <img class="d-block w-100"
                                            src="{{images.image.url}}"
                                            alt="First slide">
                                    </div>
                                    {%else%}
                                    <div class="carousel-item ">
                                        <img class="d-block w-100"
                                            src="{{images.image.url}}"
                                            alt="Second slide">
                                    </div>
                                    {%endif%}
                                    {%endfor%}
                                    
                                </div>
                                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                                    <!-- <span class="carousel-control-prev-icon" aria-hidden="true"></span> -->
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                                    <!-- <span class="carousel-control-next-icon" aria-hidden="true"></span> -->
                                    <span class="sr-only">Next</span>
                                </a>
                            </div>
            
            
            
                            <!-- <img style="width: 100%;" src="/static/image/{{room.room_image1}}" alt=""> -->
                        </td>
            
                        <td>{{room.room_type}}</td>
                        <td>{{room.room_price}}</td>
                        <td>{{room.sleeps}}</td>

                        <td>
                          <ul>
                            {%for room_features in room.room_features_set.all %}
                              {% if room_features.Free_wifi == True %}
                            <li>FREE Wifi</li>
                            {%endif%}
                            {% if room_features.king_size_bed == True %}
                            <li>king size bed</li>
                            {%endif%}
                            {% if room_features.TV == True %}
                            <li>TV</li>
                            {%endif%}
                            {% if room_features.Bath_Tube == True %}
                            <li>Bath Tube</li>
                            {%endif%}
                            {% if room_features.Welcome_bottle == True %}
                            <li>Welcome bottle</li>
                            {%endif%}
                            {% if room_features.Breakfast == True %}
                            <li>Breakfast</li>
                            {%endif%}
                            {% if room_features.Lunch == True %}
                            <li>Lunch</li>
                            {%endif%}
                            {% if room_features.Dinner == True %}
                            <li>Dinner</li>
                            {%endif%}

                            {%endfor%}
                            
                          </ul>
                        </td>
                        <td>{{room.room_available}}</td>
                        <!-- <td></td> -->
            
                        <td>
                            <a href="{%url 'room_edit' room.id %}" class="edit"><i class="material-icons" data-toggle="tooltip"
                                    title="Edit">&#xE254;</i></a>
                            <a href="{%url 'room_delete' room.id %}" class="delete" onclick="window.mytest('{{room}}')"
                                id="delcheck{{room}}" data-id="{{room.room_name}}"><i class="material-icons" data-toggle="tooltip"
                                    title="Delete">&#xE872;</i></a>
                        </td>
                    </tr>
                    {%endfor%}
            
            
            
                </tbody>
            </table>
			
        </div>
    </div>
    <script>
        var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("dot");
  if (n > slides.length) {slideIndex = 1}    
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";  
  }
  for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";  
  dots[slideIndex-1].className += " active";
}
    </script>
	
	<script>
       
        window.mytest=function(room){

          
            var v= document.getElementById("delcheck"+room)
            var roomname = v.dataset.id
           
            var isValid =confirm("are you sure do you want delete  "+roomname+" room");
            if(!isValid){
                event.preventDefault();
                alert("it wont be delete");
    
            }
            
        }
    </script>
	
	{%endblock%}