Hotel_room_book/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admn/', admin.site.urls),
    path('',include('user.urls')),
    path('admin/',include('admn.urls')),
    path('hotel/',include('hotel.urls')),
    path('accounts/',include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admn/urls.py
from django .urls import path
from . import views


urlpatterns=[ 
    path('',views.admin_login,name='admin_login'),
    path('admin_home',views.admin_home,name='admin_home'),
    path('admin_logout',views.admin_logout,name='admin_logout'),
    path('create_hotel',views.create_hotel,name='create_hotel'),
    path('hotel_view',views.hotel_view,name='hotel_view'),
    path('hotel_edit/<int:id>/',views.hotel_edit,name='hotel_edit'),
    path('hotel_delete/<int:id>/',views.hotel_delete,name='hotel_delete'),
    path('user_view',views.user_view,name='user_view'),
    path('user_edit/<int:id>/',views.user_edit,name='user_edit'),
    path('user_delete/<int:id>/',views.user_delete,name='user_delete'),
    path('refoffer',views.refoffer,name='refoffer'),
    path('offeredit/<int:id>/',views.offeredit,name='offeredit'),
    path('offerstatus/<int:id>/<str:value>/',views.offerstatus,name='offerstatus'),
    path('userBlock/<int:id>/',views.userBlock,name='userBlock'),
    path('hotelblock/<int:id>/',views.hotelblock,name='hotelblock'),
    path('vip',views.vip,name='vip'),
    path('viphotel',views.viphotel,name='viphotel'),
    path('viproom',views.viproom,name='viproom'),
    path('location',views.location,name='location'),
   path('hotel',views.hotel,name='hotel'),
    path('act/<int:id>/<str:value>/',views.act,name='act'),



]

hotel/urls.py
from django .urls import path
from . import views


urlpatterns=[ 
    path('',views.hotel_log,name='hotel_log'),
    path('hotel-home/<int:id>/',views.hotel_home,name='hotel_home'),
    path('hotel_logout',views.hotel_logout,name='hotel_logout'),
    path('hotel_rooms/<int:id>/',views.hotel_rooms,name='hotel_rooms'),
    path('add_room/<int:id>/',views.add_room,name='add_room'),
    path('hotel_profile/<int:id>/',views.hotel_profile,name='hotel_profile'),
    path('hotel_update/<int:id>/',views.hotel_update,name='hotel_update'),
    path('room_edit/<int:id>/',views.room_edit,name='room_edit'),
    path('room_delete/<int:id>/',views.room_delete,name='room_delete'),
    path('hotel_user/<int:id>/',views.hotel_user,name='hotel_user'),
    path('hotel_booked/<int:id>/',views.hotel_booked,name='hotel_booked'),
    path('booking_detail/<int:id>/',views.booking_detail,name='booking_detail'),
    path('confirm/<int:id>/<str:value>/',views.confirm,name='confirm'),


]

user/urls.py
from django .urls import path
from . import views


urlpatterns=[

    path('',views.home,name='home'),
    path('login',views.user_login,name="user_login"),
    path('mobail',views.mobile_login,name="mobile_login"),
    path('otp_generate',views.otp_generate,name='otp_generate'),
    path('register_user',views.register_user,name='register_user'),
    path('logout',views.user_logout,name="user_logout"),
    path('hotel-view/<int:id>/',views.hotel_view,name="hotel_view"),
    path('booking/<int:id>/',views.booking,name="booking"),
    path('hotel_list/<str:city>/',views.hotel_list,name='hotel_list'),
    path('booking_details/',views.booking_details,name='booking_details'),
    path('user_profile/',views.user_profile,name='user_profile'),
    path('report/<int:id>/<str:pay>/',views.report,name='report'),
    path('reffral_signup/<str:referalcode>/',views.reffral_signup,name='reffral_signup'),
    path('search',views.search,name='search'),
    path('guestreg',views.guestreg,name='guestreg')


    
    

]

admn/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.




class Hoteladmin(models.Model):

    hotel_name=models.CharField(max_length=200,null=True)
    username=models.CharField(max_length=200,null=True)
    password=models.CharField(max_length=200,null=True)
    is_active = models.BooleanField(default=True)
    location=models.CharField(max_length=200,null=True)
    contact=models.BigIntegerField()
    description=models.TextField(max_length=1000,verbose_name='description')
    categories=models.CharField(max_length=200,null=True)
    hotelimage1=models.ImageField(null=True ,blank=True)


    @property
    def get_lowest_price(self):
        try:
            rooms =self.rooms_set.all()
            price=[]
            
            for room in rooms:
                price.append(room.room_price)
            
            lowest_price=min(price)
        except:
            lowest_price='NOT ENTERD'
        return lowest_price


    @property
    def imageURL(self):
        try:
            url= self.hotelimage1.url
        except:
            url=''
        return url
            

            

class Customer(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, null=True,blank=True)
    name=models.CharField(max_length=200,null=True)
    email=models.CharField(max_length=200,null=True)
    reff_code = models.CharField(max_length=100, null= True)
    refferd_user = models.CharField(max_length=150, null= True)
    

class Features(models.Model):
    hotel=models.ForeignKey(Hoteladmin,on_delete=models.SET_NULL,null=True,blank=True)
    Free_wifi=models.BooleanField(default=False)
    Loundry_service=models.BooleanField(default=False)
    Swimming_pool=models.BooleanField(default=False)
    Restaurant=models.BooleanField(default=False)
    Parking=models.BooleanField(default=False)

class Hotel_image(models.Model):
    hotel=models.ForeignKey(Hoteladmin,on_delete=models.SET_NULL,null=True,blank=True)
    image=models.ImageField(null=True ,blank=True)

class Rooms(models.Model):
    hotel=models.ForeignKey(Hoteladmin,on_delete=models.SET_NULL,null=True,blank=True)
    room_type=models.CharField(max_length=200,null=True)
    # room_description=models.TextField(max_length=1000,verbose_name='description')
    sleeps=models.CharField(max_length=200,null=True)
    room_price=models.FloatField()
    room_image1=models.ImageField(null=True ,blank=True)
    room_image2=models.ImageField(null=True ,blank=True)
    room_image3=models.ImageField(null=True ,blank=True)
    room_available=models.IntegerField()


class Room_features(models.Model):
    hotel= models.ForeignKey(Hoteladmin,on_delete=models.SET_NULL,null=True,blank=True)
    room=models.ForeignKey(Rooms,on_delete=models.SET_NULL,null=True,blank=True)
    Free_wifi=models.BooleanField(default=False)
    king_size_bed=models.BooleanField(default=False)
    TV=models.BooleanField(default=False)
    Bath_Tube=models.BooleanField(default=False)
    Safe_box=models.BooleanField(default=False)
    Welcome_bottle=models.BooleanField(default=False)
    Breakfast=models.BooleanField(default=False)
    Lunch=models.BooleanField(default=False)
    Dinner=models.BooleanField(default=False)
    

class Room_image(models.Model):
    room=room=models.ForeignKey(Rooms,on_delete=models.SET_NULL,null=True,blank=True)
    image=models.ImageField(null=True ,blank=True)




class Booking(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.SET_NULL,null=True,blank=True)
    hotel=models.ForeignKey(Hoteladmin,on_delete=models.SET_NULL,null=True,blank=True)
    date_booked=models.DateField(auto_now=True)
    check_in=models.DateField(null=True,blank=True)
    check_out=models.DateField(null=True,blank=True)
    complete=models.BooleanField(default=False,null=True,blank=True)
    total_price=models.BigIntegerField(default=0,null=True,blank=True)
    payment_status=models.CharField(max_length=200,null=True)
    total_guest=models.CharField(max_length=200,null=True)
    cancel=models.BooleanField(default=False,null=True,blank=True)
    confirm=models.BooleanField(default=False,null=True,blank=True)
    
    @property
    def total_rooms(self):
        roombooked=self.roombooked_set.all()
        total=sum(room.quantity for room in roombooked)
        return total
        

class Roombooked(models.Model):
    room=models.ForeignKey(Rooms,on_delete=models.SET_NULL,null=True,blank=True)
    booking=models.ForeignKey(Booking,on_delete=models.SET_NULL,null=True,blank=True)
    quantity=models.IntegerField(default=0,null=True,blank=True)
    date_added = models.DateField(auto_now_add=True)
    

    @property
    def get_total(self):
        total = self.room.room_price * self.quantity
        return total




class reffreal_offer(models.Model):
    ref_name = models.CharField(null = True, max_length=225)
    ref_discount = models.IntegerField(null = True)
    ref_price = models.IntegerField(null = True)
    referd_person_discount = models.IntegerField(null = True)
    order_maximum = models.IntegerField(null = True)
    ref_status = models.BooleanField(null=True,default=True)
    offer_type=models.CharField(max_length=200,null=True)


class VIP(models.Model):
    hotel=hotel=models.ForeignKey(Hoteladmin,on_delete=models.SET_NULL,null=True,blank=True)
    room=models.ForeignKey(Rooms,on_delete=models.SET_NULL,null=True,blank=True)
    status= models.BooleanField(null=True,default=True)
    

hotel/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models

# Create your models here.

templates/user/booking.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700');

/* body{
  background: url('http://all4desktop.com/data_images/original/4236532-background-images.jpg');
  font-family: 'Roboto Condensed', sans-serif;
  color: #262626;
  margin: 5% 0;
} */
.container{
  width: 100%;
  padding-right: 15px;
  padding-left: 15px;
  margin-right: auto;
  margin-left: auto;
}
@media (min-width: 1200px)
{
  .container{
    max-width: 1140px;
  }
}
.d-flex{
  display: flex;
  flex-direction: row;
  background: #f6f6f6;
  border-radius: 0 0 5px 5px;
  padding: 25px;
}
form{
  flex: 4;
}
.Yorder{
  flex: 2;
}
.title{
  background: -webkit-gradient(linear, left top, right bottom, color-stop(0, #5195A8), color-stop(100, #70EAFF));
  background: -moz-linear-gradient(top left, #5195A8 0%, #70EAFF 100%);
  background: -ms-linear-gradient(top left, #5195A8 0%, #70EAFF 100%);
  background: -o-linear-gradient(top left, #5195A8 0%, #70EAFF 100%);
  background: linear-gradient(to bottom right, #5195A8 0%, #70EAFF 100%);
  border-radius:5px 5px 0 0 ;
  padding: 20px;
  color: #f6f6f6;
}
h2{
  margin: 0;
  padding-left: 15px; 
}
.required{
  color: red;
}
label, table{
  display: block;
  margin: 15px;
}
label>span{
  float: left;
  width: 25%;
  margin-top: 12px;
  padding-right: 10px;
}
input[type="text"], input[type="tel"], input[type="email"], select
{
  width: 70%;
  height: 30px;
  padding: 5px 10px;
  margin-bottom: 10px;
  border: 1px solid #dadada;
  color: #888;
}
select{
  width: 72%;
  height: 45px;
  padding: 5px 10px;
  margin-bottom: 10px;
}
.Yorder{
  margin-top: 15px;
  height: auto;
  padding: 20px;
  border: 1px solid #dadada;
}
table{
  margin: 0;
  padding: 0;
}
th{
  border-bottom: 1px solid #dadada;
  padding: 10px 0;
}
tr>td:nth-child(1){
  text-align: left;
  color: #2d2d2a;
}
tr>td:nth-child(2){
  text-align: right;
  color: #52ad9c;
}
td{
  border-bottom: 1px solid #dadada;
  padding: 25px 25px 25px 0;
}

p{
  display: block;
  color: #888;
  margin: 0;
  padding-left: 25px;
}
.Yorder>div{
  padding: 15px 0; 
}

.button{
  width: 50%;
  margin-top: 10px;
  padding: 10px;
  border: none;
  border-radius: 30px;
  background: #52ad9c;
  color: #fff;
  font-size: 15px;
  font-weight: bold;
  align-items: center;
}
.button:hover{
  cursor: pointer;
  background: #428a7d;
}

button{
  width: auto;
  background-color: white;
  color: black;
  
  margin-top: 10px;
  padding: 10px;
  border: none;
  border-radius: 30px;
  
  font-size: 15px;
  font-weight: bold;
  align-items: center;
}
button:hover{
  cursor: pointer;
  background: #57ad9e;
}
    </style>
    <div class="container">
        <div class="title">
          
            
            <h2>Booking details</h2>
          
        </div>
      <div class="d-flex">
        {%  if request.user.is_authenticated %}
        <form action="" method="POST">
          {%csrf_token%}
          <p>We will use these details to share your booking information</p>
          <label>
            <span class="fname">Full Name <span class="required">*</span></span>
            <input type="text" name="name" readonly value="{{booking.customer.name}}">
          </label>
          <label>
            
            <span>Phone <span class="required">*</span></span>
            <input type="tel" name="phone" value="{{user.last_name}}" readonly> 
          </label>
          <label>
            <span>Email Address <span class="required">*</span></span>
            <input type="email" name="email" value="{{booking.customer.email}}" readonly> 
          </label>
          <div>
            <button type="button" data-id="0" id="book" class="btn btn-primary" >Pay At Hotel</button>
          </div>
          <div>
            <input type="hidden" onclick="window.myt()"  id="bk" class="button" >
            
          </div>
          <div>
            <button type="button" id="paynow" >PAY NOW</button>
            <div class="box-element " style="display: none;" id="payment-info">
              
              <div id="paypal-button-container"></div>
              <button id="rzp-button1" class="btn btn-success btn-block" style="background-color: #fe980f; width: 100%;">RazorPay</button>
                           
          </div>
          </div>
          
         
        </form>
{%else%}
<form action="{% url 'guestreg' %}" method="POST">
 {% csrf_token %}
  <p>We will use these details to share your booking information</p>
  <label>
    <span class="fname">Full Name <span class="required">*</span></span>
    <input type="text" name="name" value="{{username}}">
  </label>
  <label>
    
    <span>Phone <span class="required">*</span></span>
    <input type="tel" name="mobile" value="{{mobile}}"> 
  </label>
  <label>
    <span>Email Address <span class="required">*</span></span>
    <input type="email" name="email" value="{{email}}"> 
  </label>
  <label>
    <span>Password <span class="required">*</span></span>
    <input type="text" name="password"> 
  </label>
  <div>
   <center> <input type="submit" style="background-color: #4CAF50;
    border: none;
    color: white;
    padding: 16px 32px;
    text-decoration: none;
    margin: 4px 2px;
    cursor: pointer;"></center>
  </div>
  
  {% for message in messages %}
  <p style="color: red;">{{message}}</p>
  {% endfor %}
</form>{%endif%}
{% if request.user.is_authenticated %}

        <div class="Yorder">
          <table>
            <tr>
              <th colspan="2">{{booking.hotel.hotel_name}}</th>
              <th></th>
            </tr>
            {% for bkroom in rooms %}
            {%for images in bkroom.room.room_image_set.all %}
            {%if forloop.first %}
            <tr>
              <td><h5>{{bkroom.room.room_type}}</h5><h5>Price/night:{{bkroom.room.room_price}}</h5><br> selected rooms:{{bkroom.quantity}} </td>
              <td>
                <img style="width: 100%; height: 100px;" src="{{images.image.url}}" alt="">
              </td>
            </tr>
            {%endif%}
            {%endfor%}
            {%endfor%}
            <tr>
              <td>Rooms</td>
              <td>{{booking.total_rooms}}</td>
            </tr>
            <tr>
              <td>guest</td>
              <td>{{booking.total_guest}}</td>
            </tr>
            <tr>
              <td>Days</td>
              <td>{{date.days}}</td>
            </tr>
            <tr>
              <td><h4>checkin</h4>{{booking.check_in}}</td>
              <td style="color:black"><h4 >checkout</h4>{{booking.check_out}}</td>
            </tr>
            <tr>
              <td>Price</td>
              <td>{{booking.total_price}}</td>
            </tr>
            {% if prev_book == False %}
              {% for off in ref %}
              
            <tr>
              <td>Discount</td>
              {% if off.offer_type == 'OfferByPercentage' %}
              <td>{{off.ref_discount}}%</td>
              {% else %}
              <td>{{off.ref_price}}</td>
              {% endif %}
            </tr>
            {% endfor %}
            {% endif %}
            
            <tr>
              <td>Total</td>
              <td>{{booktotal}}</td>
            </tr>
           
          </table><br>
          
          
        </div><!-- Yorder -->
    {% else %}
        <div class="Yorder">
          <table>
            <tr>
              <th colspan="2">{{hotel.hotel_name}}</th>
              <th></th>
            </tr>
            
            {% for bkroom,count in zip %}
            
            
            {%for images in bkroom.room_image_set.all %}
            {%if forloop.first %}
            
            <tr>
              <td><h5>{{count.room.room_type}}</h5><h5>Price/night:{{bkroom.room_price}}</h5><br> {% if count.room == bkroom %} selected rooms:{{count.count}}  {% endif %} </td>
              <td>
                <img style="width: 100px;" src="{{images.image.url}}" alt="">
              </td>
            </tr>
            
            {%endif%}
            {%endfor%}
            {%endfor%}
            <tr>
              <td>Rooms</td>
              <td>{{total_rooms}}</td>
            </tr>
            <tr>
              <td>guest</td>
              <td>{{total_guest}}</td>
            </tr>
            <tr>
              <td>Days</td>
              <td>{{total_days}}</td>
            </tr>
            <tr>
              <td><h4>checkin</h4>{{checkin}}</td>
              <td style="color:black"><h4 >checkout</h4>{{checkout}}</td>
            </tr>
            <tr>
              <td>Price</td>
              <td>{{total_price}}</td>
            </tr>
            
            
            <tr>
              <td>Total</td>
              <td>{{total_price}}</td>
            </tr>
           
          </table><br>
          
          
        </div><!-- Yorder -->
        {% endif %}
       </div>
      </div> 
     

</body>




<script>
  var book=document.getElementById("book")
  
  book.addEventListener('click',function(){
    document.getElementById("payment-info").style.display='none'
    document.getElementById("bk").setAttribute('type','submit');
    document.getElementById("bk").setAttribute('formaction','/report/{{booking.id}}/COD/');

  })
  window.myt=function(){
    alert("booking is confirmed ")
  }


  var paynow=document.getElementById("paynow")
  paynow.addEventListener("click",function(){
    document.getElementById("bk").setAttribute('type','hidden');
    document.getElementById("payment-info").style.display='block'
  })

</script>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
    var total ='{{booktotal}}'
    var payment_status='razorpay'
    var options = {
        "key": "rzp_test_7i01eG7knm1628", // Enter the Key ID generated from the Dashboard
        "amount": total, // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
        "currency": "INR",
        "name": "Acme Corp",
        "description": "Test Transaction",
        "image": "https://example.com/your_logo",
        "order_id": "{{order_id}}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
        "handler": function (response){
           
          window.location.href="/report/{{booking.id}}/RAZOR/"
        },
        "prefill": {
            "name": "Gaurav Kumar",
            "email": "gaurav.kumar@example.com",
            "contact": "9999999999"
        },
        "notes": {
            "address": "Razorpay Corporate Office"
        },
        "theme": {
            "color": "#F37254"
        }
    };
    var rzp1 = new Razorpay(options);
    document.getElementById('rzp-button1').onclick = function(e){
        rzp1.open();
        e.preventDefault();
    }
    </script>
     <script src="https://www.paypal.com/sdk/js?client-id=AYtodiSdVNbDP1Kn-G9ScgW79r5dczXhaDzz5gT8a1Jm-TB4tn9a5soO5rcNP7Q104W5s8iJoE7Es7ot&currency=USD&disable-funding=card"></script>
     <script>
         var total ='{{booktotal}}'
        
         // Render the PayPal button into #paypal-button-container
         paypal.Buttons({
             
 
             // Set up the transaction
             createOrder: function(data, actions) {
                 return actions.order.create({
                     purchase_units: [{
                         amount: {
                             value: parseFloat(total).toFixed(2)
                         }
                     }]
                 });
             },
 
             // Finalize the transaction
             onApprove: function(data, actions) {
                 return actions.order.capture().then(function(details) {
                  window.location.href="/report/{{booking.id}}/PAY/"
                 });
             }
 
 
         }).render('#paypal-button-container');
     </script>
</html>

templates/user/mobile_login.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport"
    content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Travelix</title>
  <!--Font awesome CDN-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
  <link rel="stylesheet" href="{% static 'user/login/css/main.css' %}">
</head>

<body>

  <div class="hero">
    <div class="form-box">
      <h4 class="heading">login</h4>

      <div class="social-icons">
        <div class="social-media">
          <a href="#" class="sm-link"><i class="fab fa-google-plus-g"></i></a>
          <a href="#" class="sm-link"><i class="fab fa-facebook-square"></i></a>



        </div>
      </div>

      <form id="login" class="input-group" action="{% url 'mobile_login' %}" method="POST">
        {% csrf_token %}

        <input type="text" class="input-field" name="mobile" id="mobile_reg" placeholder="Mobile" required>
        <a href=""><button class="submit-btn" id="verify" >verify</button></a>

        <input type="hidden"  class="input-field" id="otp" name="otp" placeholder="OTP" required>

        <h5 style="display: block; text-align: center;"></h5>
        
        <button class="submit-btn" type="submit" style=" margin-top: 25px;">Log In</button>
        <p style="color: red;">{{error}}</p>
        {%for message in messages %}
        <p style="color: red;">{{message}}</p>
    {%endfor%}
    <a href="/login" style="margin: auto;" class="sm-link"><i class="fas fa-arrow-left"></i></a>

      </form>
    </div>
  </div>

  <script src="{% static 'user/login/js/main.js' %}"></script>
  <script src="{% static 'user/login/js/otp.js' %}"></script>
</body>

</html>

templates/user/referalreg.html
{% load static %}
{% load socialaccount %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Travelix</title>
    <!--Font awesome CDN-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'user/login/css/main.css' %}">
</head>
<body>
    
    <div class="hero">
       

        
        <div class="form-box">
            <center><h3 style="color:violet;">REGISTER</h3></center>
          <form id="login" class="input-group" method="POST" action="{% url 'reffral_signup' refcode %}">
            
                
            {% csrf_token %}
            <input type="text" class="input-field" name="username" value="{{username}}" placeholder="Username" required>
            <input type="email" class="input-field" name="email" placeholder="Email" value="{{email}}" required>
            
            <input type="text" class="input-field" name="password" placeholder="Password" required>
            <div class="mobailfield" style="display: flex;">
              <input type="text" class="input-field" id="mobile_reg" name="mobile" placeholder="Mobail" pattern="[6-9]{1}[0-9]{9}" required></div>
            <!--
                <a href="" ><button class="submit-btn" id="verify">verify</button></a>
                </div>
                <input type="hidden" id="otp" name="otp" class="input-field" placeholder="OTP" required> -->
                <span class="check-box"></span>
            <button class="submit-btn" type="submit" style=" margin-top: 25px;">Register</button>
            {%for message in messages %}
                <p style="color: red;">{{message}}</p>
            {%endfor%}
            
          </form>
        </div>
      </div>
      
<script src="{% static 'user/login/js/main.js' %}"></script>
<script src="{% static 'user/login/js/otp.js' %}"></script>
</body>
</html>

templates/user/useraccount.html
{% extends 'user/base.html' %}
{% load static %}
{% block content%}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <div class="container">
    <div class="row" style="height: 15rem;">
      
      <div class="col-xs-12">
        <div class="box">
          <p></p>
        </div>
      </div>
  
    </div>
    <div>
      {% if value == True %}
        {% for off in ref %}
     
         <h1><center style="color:green;">CONGRATS YOU HAVE <span style="color: blue;"> {% if off.offer_type == 'OfferByPercentage' %}{{off.ref_discount}}% {% else %}{{off.ref_price}} Rupees {% endif %}</span>  DISCOUNT  ON FIRST BOOK</center></h1>
        {% endfor %}
      {% endif %}
    </div>
    <div class="row " style="height: 25rem;">
      <div class="col-md-4 border">
        <div class="text-center">
          <h4>FULL NAME</h4>
          <p>{{customer.name}}</p>
          <h4>Mobile Number</h4>
          <p>{{user.last_name}}</p>
          <h4>email</h4>
          <p>{{user.email}}</p>
          <h4>Refferal Code</h4>
          <p><a href="">{{ request.META.HTTP_HOST }}/{{"reffral_signup"}}/{{customer.reff_code}}</a></p>
          <h1>Wallet:{{wallet}}</h1>
          <p style="color: blue;">Please refer someone using Referel Code  and get 100 rupees</p>
        </div>
      </div>
      <div class="col-md-8 border">
        <h4>BOOKING HISTORY</h4>
        <table class="table table-striped">
          <thead>
            <tr>
              
              <th colspan=2></th>
              <th scope="col"></th>
              <th scope="col"></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for booking in customer.booking_set.all %}
            {% if booking.complete == True %}
            <tr>
            
            
            
              <td colspan=2><img src="{{booking.hotel.hotelimage1.url}}" style="height:100px; width: 100px;" alt=""></td>
            
  
          
              <td>{{booking.hotel.hotel_name}}</td>
              <td>{{booking.id}}</td>
              {%if booking.payment_status == 'Pay at hotel' %}
              <td><h5>Confirm Booking</h5>
                <p>Pending Amount: ₹764</p>
                 </td>
                 {%else%}
                 <td><h5 style="color: blue;">Booking is Confirmed</h5>
                  
                   </td>
                   {%endif%}

                 <td><a href="{%url 'report' booking.id booking.payment_status %}">view details</a></td>
           </tr>
           {% endif %}
           {%endfor%}
          </tbody>
        </table>

      </div>
      

    </div>
    <div class="row" style="height: 15rem;">
      
      <div class="col-xs-12">
        <div class="box">
          <p></p>
        </div>
      </div>
  
    </div>
  </div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{%endblock%}